# Generated by Django 6.0.5 on 2026-06-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('price', models.IntegerField(max_length=100)),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('shoes', 'Shoes'), ('linen Co-ord Set', 'Linen Co-ord Set'), ('Modern Kurta', 'Modern kurta'), ('slip Dress', 'Slip Dress')], max_length=100)),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='details/')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='details/')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='details/')),
            ],
        ),
    ]
