# Generated by Django 6.0.5 on 2026-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.IntegerField(),
        ),
    ]
